// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CharBlock: typeof import('./src/components/CharBlock.vue')['default']
    Hint: typeof import('./src/components/Hint.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Sentence: typeof import('./src/components/Sentence.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    WelcomePage: typeof import('./src/components/WelcomePage.vue')['default']
  }
}

export { }
