// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppName: typeof import('./src/components/AppName.vue')['default']
    CharBlock: typeof import('./src/components/CharBlock.vue')['default']
    CheatSheet: typeof import('./src/components/CheatSheet.vue')['default']
    Confetti: typeof import('./src/components/Confetti.vue')['default']
    Countdown: typeof import('./src/components/Countdown.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DashboardItem: typeof import('./src/components/DashboardItem.vue')['default']
    FailedPage: typeof import('./src/components/FailedPage.vue')['default']
    FeedbackLinks: typeof import('./src/components/FeedbackLinks.vue')['default']
    Hint: typeof import('./src/components/Hint.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModalsLayer: typeof import('./src/components/ModalsLayer.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NoFuturePlay: typeof import('./src/components/NoFuturePlay.vue')['default']
    NoPastPlay: typeof import('./src/components/NoPastPlay.vue')['default']
    NoQuizToday: typeof import('./src/components/NoQuizToday.vue')['default']
    NotTodayBanner: typeof import('./src/components/NotTodayBanner.vue')['default']
    Play: typeof import('./src/components/Play.vue')['default']
    ResultFooter: typeof import('./src/components/ResultFooter.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    ShareButton: typeof import('./src/components/ShareButton.vue')['default']
    ShareDialog: typeof import('./src/components/ShareDialog.vue')['default']
    ShareImage: typeof import('./src/components/ShareImage.vue')['default']
    ShareText: typeof import('./src/components/ShareText.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    ToggleMask: typeof import('./src/components/ToggleMask.vue')['default']
    ToneSymbol: typeof import('./src/components/ToneSymbol.vue')['default']
    VariantLinks: typeof import('./src/components/VariantLinks.vue')['default']
    VDots: typeof import('./src/components/VDots.vue')['default']
    WelcomePage: typeof import('./src/components/WelcomePage.vue')['default']
    WordBlocks: typeof import('./src/components/WordBlocks.vue')['default']
  }
}
