// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CharBlock: typeof import('./src/components/CharBlock.vue')['default']
    Sentence: typeof import('./src/components/Sentence.vue')['default']
  }
}

export { }
